// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFDataFirstLIbrary.Models
{
    [Table("Employee")]
    public partial class Employee
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Gender { get; set; }
        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string Address { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Qualification { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Experience { get; set; }
        public int? EmlpoyeeTeamId { get; set; }

        [ForeignKey("EmlpoyeeTeamId")]
        [InverseProperty("Employees")]
        public virtual Team EmlpoyeeTeam { get; set; }
    }
}