// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFDataFirstLIbrary.Models
{
    public partial class Team
    {
        public Team()
        {
            Employees = new HashSet<Employee>();
        }

        [Key]
        public int TeamId { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string TeamName { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Batch { get; set; }
        public int? TeamCompanyId { get; set; }

        [ForeignKey("TeamCompanyId")]
        [InverseProperty("Teams")]
        public virtual CompanyInfo TeamCompany { get; set; }
        [InverseProperty("EmlpoyeeTeam")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}