// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShoppingCartApplication.Models.Entity
{
    [Table("Category")]
    public partial class Category
    {
        public Category()
        {
            Items = new HashSet<Item>();
        }

        [Key]
        public int CategoryId { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string CategoryCode { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string CategoryName { get; set; }

        [InverseProperty("Category")]
        public virtual ICollection<Item> Items { get; set; }
    }
}