// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShoppingCartApplication.Models.Entity
{
    [Table("Item")]
    public partial class Item
    {
        [Key]
        public int ItemId { get; set; }
        public int? CategoryId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ItemCode { get; set; }
        [StringLength(250)]
        public string ItemName { get; set; }
        [StringLength(250)]
        public string Description { get; set; }
        [StringLength(550)]
        public string ImagePath { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? ItemPrice { get; set; }

        [ForeignKey("CategoryId")]
        [InverseProperty("Items")]
        public virtual Category Category { get; set; }
    }
}