// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBFirstLayer.Models
{
    [Table("Class")]
    public partial class Class
    {
        public Class()
        {
            Exams = new HashSet<Exam>();
            Expenses = new HashSet<Expense>();
            Fees = new HashSet<Fee>();
            StudentAttendances = new HashSet<StudentAttendance>();
            Students = new HashSet<Student>();
            Subjects = new HashSet<Subject>();
            TeacherSubjects = new HashSet<TeacherSubject>();
        }

        [Key]
        public int ClassId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ClassName { get; set; }

        [InverseProperty("Class")]
        public virtual ICollection<Exam> Exams { get; set; }
        [InverseProperty("Class")]
        public virtual ICollection<Expense> Expenses { get; set; }
        [InverseProperty("Class")]
        public virtual ICollection<Fee> Fees { get; set; }
        [InverseProperty("Class")]
        public virtual ICollection<StudentAttendance> StudentAttendances { get; set; }
        [InverseProperty("Class")]
        public virtual ICollection<Student> Students { get; set; }
        [InverseProperty("Class")]
        public virtual ICollection<Subject> Subjects { get; set; }
        [InverseProperty("Class")]
        public virtual ICollection<TeacherSubject> TeacherSubjects { get; set; }
    }
}