// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBFirstLayer.Models
{
    public partial class Fee
    {
        [Key]
        public int FeesId { get; set; }
        public int? ClassId { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? FeesAmount { get; set; }

        [ForeignKey("ClassId")]
        [InverseProperty("Fees")]
        public virtual Class Class { get; set; }
    }
}