// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBFirstLayer.Models
{
    [Table("StudentAttendance")]
    public partial class StudentAttendance
    {
        [Key]
        public int Id { get; set; }
        public int? ClassId { get; set; }
        public int? SubjectId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string RollNo { get; set; }
        public bool? Status { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Date { get; set; }

        [ForeignKey("ClassId")]
        [InverseProperty("StudentAttendances")]
        public virtual Class Class { get; set; }
        [ForeignKey("SubjectId")]
        [InverseProperty("StudentAttendances")]
        public virtual Subject Subject { get; set; }
    }
}