// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBFirstLayer.Models
{
    [Table("Teacher")]
    public partial class Teacher
    {
        public Teacher()
        {
            TeacherAttendances = new HashSet<TeacherAttendance>();
            TeacherSubjects = new HashSet<TeacherSubject>();
        }

        [Key]
        public int TeacherId { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column("DOB", TypeName = "date")]
        public DateTime? Dob { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Gender { get; set; }
        public long? Mobile { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Email { get; set; }
        [Unicode(false)]
        public string Address { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Password { get; set; }

        [InverseProperty("Teacher")]
        public virtual ICollection<TeacherAttendance> TeacherAttendances { get; set; }
        [InverseProperty("Teacher")]
        public virtual ICollection<TeacherSubject> TeacherSubjects { get; set; }
    }
}