// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DBFirstLayer.Models
{
    [Table("TeacherAttendance")]
    public partial class TeacherAttendance
    {
        [Key]
        public int Id { get; set; }
        public int? TeacherId { get; set; }
        public bool? Status { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Date { get; set; }

        [ForeignKey("TeacherId")]
        [InverseProperty("TeacherAttendances")]
        public virtual Teacher Teacher { get; set; }
    }
}